server:
  host-port: ":8080"
  base-router: "/ez-todo/api"

mysql:
  path: "127.0.0.1"
  port: "3306"
  dbname: "ez_todo"
  username: "root"
  password: "123456"
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  max-idle-conns: 10
  max-open-conns: 100
  table-prefix: "todo_"
  singular-table: true
  log-mode: "info"
  engine: "InnoDB"

jwt:
  signing-key: "B697F829E18748FCBD6067BB29054FAB"
  expires-time: "7d"
  buffer-time: "1d"
  issuer: "seven@example.com"

# lumberjack [配置详情](https://github.com/natefinch/lumberjack/tree/v2.0)
lumberjack:
  max-size: 20
  backups: 5
  max-age: 30
  compress: true
